version: '3'

services:
    ecommerce:
        image: registry.gitlab.com/georgericardo26/ecommerce
        command: python manage.py runserver 0.0.0.0:8000
        container_name: ecommerce
        volumes:
            - .:/code
        ports:
            - "8000:8000"
