# Generated by Django 2.2.4 on 2019-08-12 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brand_extraproducttype_product_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deleted_in', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_request', to='main.Client')),
                ('products', models.ManyToManyField(blank=True, related_name='product_request', to='main.Product')),
            ],
        ),
    ]
