# Generated by Django 2.2.4 on 2019-08-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190812_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraproducttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='extraproducttype',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
