# Generated by Django 2.2.4 on 2019-08-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190812_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproducttype',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
