# Generated by Django 2.2.4 on 2019-08-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_extraproducttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
