# Generated by Django 2.2.4 on 2019-08-13 14:59

from django.db import migrations
import django_resized.forms
import main.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_producttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to=main.helpers.path_and_rename_product),
        ),
    ]
