# Generated by Django 2.2.4 on 2019-08-14 17:37

from django.db import migrations
import django_resized.forms
import main.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to=main.helpers.path_and_rename_product),
        ),
    ]
