# Generated by Django 2.2.4 on 2019-08-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190814_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_request', to='main.Product'),
        ),
    ]
