# Generated by Django 2.2.4 on 2019-08-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190814_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
